### ISSUE TITLE
Tab Groups addon incompatibility

### ISSUE THREAD

**Issue by berkley4** [sblask/firefox-tab-deque#6]
Although I was aware of Tab Deque's incompatibility with Tab Groups, I opened an issue on the Tab Groups github to see if it could be fixed at their end.

The Tab Groups author has responded that they'd be interested in fixing the incompatibility, but they can't do so without Tab Deque being modified.

It would be great if both addons could work together, and if you're interested the issue is here - https://github.com/Quicksaver/Tab-Groups/issues/294

**Comment by sblask** [comment]
As I commented in the issue, I don't think there is something I can do about it.

**Comment by sergeevabc** [comment]
Hmmm… Also your addon does not play nicely with [PanoramaTabGroups][1] by @projectdelphai.

[1]: https://github.com/projectdelphai/panorama-tab-groups

**Comment by Neytrino-OnLine** [comment]
Maybe Tab Deque could ignore panorama add-ons tabs (removing it from the list)

**Comment by sblask** [comment]
As I said earlier, if Tab Deque doesn't work with another add-on it's probably because the add-on does a lot of special things and I can't do anything about. And even if, I won't add loads of functionality that is special for some add-ons that I don't use. It's probably easier to include Tab Deque's functionality in the other add-on. I will lock this issue now.

**Comment by Neytrino-OnLine** [comment]
I think you could just add to settings an option to add the URL's (e.g. moz-extension://477019a6-f567-4c53-a74d-9eb16cf73136/view.html) that should to be removed from the list automatically. This is may solve this problem. But if you essentially do not want to do it...
