### ISSUE TITLE
Add support for multiprocess (e10s)

### ISSUE THREAD

**Issue by animehunter** [sblask/firefox-tab-deque#7]
Can you add support for e10s please?

Thank you.

**Comment by sblask** [comment]
I'd love to if only it were that simple. One of the main features for me is being able to click to send a tab to the end of the queue. This is what will stop immediately if I just enable multiprocessing. A migration to webextensions won't help because there is no API to detect clicks on tabs. At the end of this year the current form of this add-on will stop working because Mozilla will deprecate everything but webextensions. Most likely many other add-ons will stop working too. I might just migrate to Vivaldi which has everything this add-on does built-in.

**Comment by animehunter** [comment]
Thank you for the suggestion. I'll give Vivaldi a try.

**Comment by sblask** [comment]
I have a webextension compatible version now, but it won't work on Firefox because of https://bugzilla.mozilla.org/show_bug.cgi?id=1366290 ...

**Comment by boldcompany** [comment]
Sebastian, thanks for all your hard work on this. I hope Firefox gets back to realizing why users like the browser in the first place - the possibility of customization via add-ons!
